### ISSUE TITLE
Hugo TODO

### ISSUE THREAD

**Issue by XhmikosR** [twbs/blog#231]
TODO:

- [ ] social: add back `og:site_name=Bootstrap Blog`?
- [ ] vnu:
  - [x] ignore the duplicate IDs errors
  - [ ] report the issue upstream in Hugo
- [ ] canonical URL is wrong for paginated pages
- [ ] paginated pages are not included in sitemap
- [ ] link rel/next are missing
- [ ] fix subnav archive `.active` check; now it matches the paginated pages too -  EDIT: I guess we can live with that?

For later:

- [ ] archetypes
- [ ] `partialCached`
- [x] add native lazyload for images? Alternatively, use a render hook to add `.lazy` in all images
- [x] add `img-fluid` class to images and remove custom CSS?
- [ ] see if it's fast to generate responsive images with Hugo
- [x] move JS deps to npm
- [x] move Bootstrap to npm
- [ ] json+ld: https://codingnconcepts.com/hugo/structure-data-json-ld-hugo/
